### PR TITLE
Add options for ERS and Opmon

### PR DESCRIPTION
**Pull request by eflumerf**
This PR includes the changes in #63 

Add `--opmon-impl`, `--ers-impl`, `--pocket-url`, and `--partition_name` options to `mdapp_multiru_gen`

### CODE REVIEW

**Comment by bieryAtFnal** [comment]
I'm working on validating the --opmon-impl cern option...

**Comment by bieryAtFnal** [comment]
I suspect that I have been successful running with the "--opmon-impl cern" option, but I haven't completely verified that yet.  The reason that I'm hopeful is that I don't see lots of "Cannot post to Influx DB" messages in the logs.  However, I haven't figured out how to see the metrics in Grafana.
I have run nanorc instances on np04-srv-013.cern.ch and mu2edaq13.fnal.gov.
I've run the browser on lxplus and used URL https://np04-srv-009:3000.

One bit of trivia that I should reproduce before mentioning it to anyone is that the system seemed to have trouble loading the influxOpmonService plugin on np04-srv-002.

**Comment by mroda88** [comment]
First attempt. 
I simply run the following very basic configuration 
```bash
python -m minidaqapp.nanorc.mdapp_multiru_gen --opmon-impl cern     test_cern
```
After the boot, the system becomes unstable and randomly, after a few seconds, all the applications die:
```
 [15:26:52] INFO     dataflow process exited with exit code 134   
           INFO     ruemu0 process exited with exit code 134 
           INFO     trigger process exited with exit code 134   
           INFO     hsi process exited with exit code 134   
```
If I type quickly I manage to reach the `running` status, so the error seems not to be related to a specific state. 
Looking into the logs, that is due to 
```
2021-Jul-21 15:26:52,491 ERROR [static void ers::ErrorHandler::SignalHandler::action(int, siginfo_t*, void*) at /scratch/patch-dev/sourcecode/ers/src/ErrorHandler.cpp:90] Got signal 11 Segmentation fault (invalid memory reference)
        Parameters = 'name=Segmentation fault (invalid memory reference)' 'signum=11' 
        Qualifiers = 'unknown' 
        host = np04-srv-028
        user = maroda (103984)
        process id = 73604
        thread id = 73676
        process wd = /nfs/home/maroda/DAQ/Graphics
        stack trace of the crashing thread:
          #0  /nfs/home/maroda/DAQ/Graphics/install/appfwk/lib64/libappfwk.so(typeinfo for nlohmann::detail::output_string_adapter<char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >+0) [0x7f45534b0b18]
          #1  /lib64/libpthread.so.0(+0xf5f0) [0x7f455127d5f0]
          #2  /nfs/home/maroda/DAQ/Graphics/install/appfwk/lib64/libappfwk.so(typeinfo for nlohmann::detail::output_string_adapter<char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >+0) [0x7f45534b0b18]
bash: line 1: 73604 Aborted                 (core dumped) daq_application --name ${APP_NAME} -c ${CMD_FAC} -i ${INFO_SVC}
```

**Comment by carloschavez** [comment]
Hi,  I have managed to run the most basic configuration on lxplus (not np04), the only options that I used were

**Comment by mroda88** [comment]
I can confirm that with this branch

1. default (no options)
2. cern configuration both for opmonlib and erc are working. Tried also separately and both work as expected.

So think the next step is trying pocket, but we need coordination with Giovanna.

**Review by mroda88 — APPROVED** [review]
The new feature were tested expect for the pocket options. But following the meeting, I think this is good to do and when giovanna is ready, we can test the pocket.

**Pull request merged**
