### PR TITLE
Feature/hsi hw readout

### PR DESCRIPTION
**Pull request by strilov**

### CODE REVIEW

**Review by bieryAtFnal — COMMENTED** [review]
These changes look good to me.

I've confirmed that the configuration files generated with the updated mdapp_multiru_gen.py script (with the --fake-hsi option) give similar files as the older version before the addition of the --fake-hsi option (modulo the change to use the "daq_application_ups" exec for the HSI app).

I've also verified that the data file that is created in a short run with the new --fake-hsi configuration looks good.  

I created a configuration that uses a real HSI, and that seems reasonable, although I wonder if we need to suppress the TimeSync queues in the Readout App when a real HSI is in use.  In any case, I haven't run any tests with real HSI electronics.  Is it possible for an average user to run tests with real HSI electronics?  If so, please let me know how to do that.

**Comment by strilov** [comment]
Thanks a lot Kurt. Yes, it's certainly possible to run with real HSI hardware. I'll put something instructions together, and let you know.

**Comment by strilov** [comment]
Hi Kurt. I've together some instructions here on configuring and reading out HSI hardware. If you have a chance, please feel free to try them out (you'll need the latest `develop` of `timing`, `timinglibs`, as well as the latest from this branch.

We can discuss more tomorrow.

**Comment by bieryAtFnal** [comment]
Hi Stoyan, thanks for the instructions and the note that let me know about them.

I added a short comment to those instructions to hopefully raise awareness that different versions of readout and trigger are needed for the HSI-related work than what is described on the v2.6 software area instructions.  I also added a post to the np04-daq-integration Slack channel to try to explain what is going on.  I hope that my comments help people, rather than make things more confusing.  In any case, I haven't yet managed to try a real-HSI test cause I was messing around with builds.

**Review by bieryAtFnal — APPROVED** [review]
This looks good to me, but I'll admit that I have only run --fake-hsi tests so far.

**Comment by strilov** [comment]
Thanks @bieryAtFnal. I can redo tests from the demo earlier. Apart from that, do we want to do any other tests?

**Comment by bieryAtFnal** [comment]
No, I think that if you feel that the merged script looks good, then we're good to go.

I looked at your additions to the CLI help, and those look good.  I appreciate the change to make --fake-hsi default True.

**Comment by strilov** [comment]
No problem. I've actually just pushed another commit, to make the flag more explicit (it still defaults to fake HSI).

If you are happy with the last commit, I think we can merge. I've verified that the earlier test with real HSI still works.

**Comment by bieryAtFnal** [comment]
Could we change the Default for the hw vs. fake option to specify "fake" somehow?

The existing default text of "false" is a little hard to know what that means...

```
  --hw-hsi / --fake-hsi           Flag to control whether fake or real
                                  hardware HSI config is generated  [default:
                                  False]
```

Thanks!

**Comment by strilov** [comment]
How about something like below?

`@click.option('--use-hsi-hw', default=False, help='Flag to control whether fake or real hardware HSI config is generated. Default is fake')`

That way it's more consistent with the `--use-felix` flag.

**Comment by bieryAtFnal** [comment]
Sure, that would be OK

**Comment by strilov** [comment]
OK, done.

**Pull request merged**
