### PR TITLE
removed the --disable-data-storage option from nanorc-based confgen files

### PR DESCRIPTION
**Pull request by bieryAtFnal**
since that disabling is handling within the nanorc start command.

### CODE REVIEW

**Comment by eflumerf** [comment]
Can you say just a few more words about this? Does `nanorc`'s start command take options now? What is the syntax? I'm just asking because this change takes out the part of the confgen that inserts the data storage enable/disable into the start command parameters, and I don't know the replacement functionality.

**Comment by bieryAtFnal** [comment]
Yes, sorry, nanorc start has the following usage

```
Usage: start [OPTIONS] RUN

  Starts the run

  RUN: run number

Options:
  --disable-data-storage / --enable-data-storage
                                  Toggle data storage
```

I found this when a ran a test in which I told the confgen script to disable data storage and then discovered that the value for this in the JSON file was ignored when I ran the system with those JSON files.

**Comment by bieryAtFnal** [comment]
Here is a sample nanorc command

nanorc mdapp_3proc boot init conf start --disable-data-storage 111 wait 2 resume wait 30 pause wait 2 stop scrap terminate

**Review by eflumerf — APPROVED** [review]
Thanks!

**Pull request merged**
