### PR TITLE
Eflumerf/3proc configgen

### PR DESCRIPTION
**Pull request by eflumerf**
Also includes multiproc config for running multiple readout units

### CODE REVIEW

**Comment by bieryAtFnal** [comment]
My sense is that we have a bit of version skew...

Using the confgen files on the eflumerf/3proc_configgen branch of the minidaqapp repo...

When I try to run a system configuration generated from the older (2-process) mdapp_gen.py confgen file with nanorc v1.0.0, that doesn't work.  However, a configuration generated from the new mdapp_3proc_gen.py works fine.

The reverse is true for nanorc v1.1.1.  

Would it make sense to update mdapp_3proc_gen.py and mdapp_multiproc_gen.py to work with nanorc v1.1.1?  My sense is that there are some "exec"/"daq_application" content that needs to be added...  I can work on that, if that would be helpful...

**Comment by bieryAtFnal** [comment]
Given our current preference for nanorc-based confgen files, I wonder if the python/minidaqapp/ruro_df_trg.py script should be removed.

**Comment by ngiangia** [comment]
Configuration file and readout application tested with FELIX (single and multiple RUs)

**Comment by eflumerf** [comment]
`python -m minidaqapp.nanorc.mdapp_3proc_gen 3proc_cfg`
`python -m minidaqapp.nanorc.mdapp_multiproc_gen --host-ru localhost multiproc_cfg`

```
(dbt-pyvenv) [eflumerf@ironvirt7 dev-v2.4.0]$ diff -r 3proc_cfg/ multiproc_cfg/
diff -r 3proc_cfg/boot.json multiproc_cfg/boot.json
6c6
<             "port": 3335
---
>             "port": 3334
11c11
<             "port": 3334
---
>             "port": 3335
diff -r 3proc_cfg/data/dataflow_conf.json multiproc_cfg/data/dataflow_conf.json
85c85
<                     "address": "tcp://{host_df}:12349",
---
>                     "address": "tcp://{host_df}:12347",
97c97
<                     "address": "tcp://{host_df}:12350",
---
>                     "address": "tcp://{host_df}:12348",
109c109
<                     "address": "tcp://{host_ru}:12348",
---
>                     "address": "tcp://{host_ru0}:12350",
113c113
<             "match": "ntoq_fragments_3"
---
>             "match": "ntoq_fragments_5"
diff -r 3proc_cfg/data/dataflow_init.json multiproc_cfg/data/dataflow_init.json
108c108
<             "inst": "ntoq_fragments_3",
---
>             "inst": "ntoq_fragments_5",
diff -r 3proc_cfg/data/ruemu0_conf.json multiproc_cfg/data/ruemu0_conf.json
8c8
<                     "address": "tcp://{host_ru}:12348",
---
>                     "address": "tcp://{host_ru0}:12350",
20c20
<                     "address": "tcp://{host_ru}:12347",
---
>                     "address": "tcp://{host_ru0}:12349",
78c78
<                     "address": "tcp://{host_df}:12349",
---
>                     "address": "tcp://{host_df}:12347",
89c89
<                     "address": "tcp://{host_df}:12350",
---
>                     "address": "tcp://{host_df}:12348",
diff -r 3proc_cfg/data/trgemu_conf.json multiproc_cfg/data/trgemu_conf.json
52c52
<                     "address": "tcp://{host_ru}:12347",
---
>                     "address": "tcp://{host_ru0}:12349",
56c56
<             "match": "ntoq_timesync_2"
---
>             "match": "ntoq_timesync_4"
diff -r 3proc_cfg/data/trgemu_init.json multiproc_cfg/data/trgemu_init.json
62c62
<             "inst": "ntoq_timesync_2",
---
>             "inst": "ntoq_timesync_4",
(dbt-pyvenv) [eflumerf@ironvirt7 dev-v2.4.0]$ 
```

Based on this demonstration of the equivalency of the two generators, I will remove the 3proc_gen in favor of multiproc_gen.

**Pull request merged**
