### PR TITLE
TRBuilder configration

### PR DESCRIPTION
**Pull request by mroda88**
Here is the change in the configuration in order to use the TRBuilder. At the moment, this overrides the old configuration.
I think here we might need to think if we want to keep supporting both separate and unified Module or just the unifided one.

Here is the list of things ready
- [x] configuration for minidaq-app all in a single process
- [x] configuration for 2 processes
- [x] configuration for 3 processes

Tests for single process:
- [x] run the default for O(10) minutes
- [x] high frequency stress test (up to O(50) Hz)
- [x] high number of link O(20)

Tests for 2 processes:
- [x] run the default for O(10) minutes
- [x] high frequency stress test (up to O(50) Hz)
- [x] high number of link O(20)

Tests for 3 processes:
- [x] run the default for O(10) minutes
- [x] high frequency stress test (up to O(50) Hz)
- [x] high number of link O(20)

### CODE REVIEW

**Comment by mroda88** [comment]
In the one process configuration, with a lot of links, at the stop transition, I see 
```bash
2021-Apr-27 15:37:43,295 WARNING [dunedaq::readout::ReadoutModel<RawType>::run_timesync(...) at /user/mroda/MyStore/Software/DAQ/TRBuilder/sourcecode/readout/src/ReadoutModel.hpp:242]  Failed attempt to write to the queue: timesync message queue. Data will be lost!
	was caused by: 2021-Apr-27 15:37:43,295 ERROR [FollyQueueType>::push(...) at /cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/products/appfwk/v2_2_2/slf7.x86_64.e19.prof/appfwk/include/appfwk/FollyQueue.hpp:54] time_sync_q: Unable to push within timeout period (timeout period was 0 milliseconds)
```

I tried to move around the order of the distribution of the stop command among the modules but the problem is still there. I suspect we need a finer transition with respect to what it is implemented now in the TRBuilder, but I don't have a plan now. 
I'm not even sure the solution should be looked in a different implementation or somewhere else. 
I suspect this will require some discussion.

**Comment by eflumerf** [comment]
The changes to the python files look reasonable. I think the plan is to move forward with the combined module, so I don't think we need to retain backwards-compatibility code.

**Comment by bieryAtFnal** [comment]
I found, and hopefully fixed, a minor issue with the "trb" module name in nanorc/dataflow_gen.py (RequestGenerator needed to be changed to TriggerRecordBuilder).  Before this change, I couldn't get a 3-process system (one RU) to work, and after the change, I could get that to work.

Marco, please check that I did this correctly, when you get a chance.

**Comment by mroda88** [comment]
Hi @bieryAtFnal yes tour changes are ok. Since I haven't tried yet the multi-process configuration, I only checked that the python syntax was correct. 
Thanks

**Comment by bieryAtFnal** [comment]
Hi Marco, yes, I recall that we talked about needing to go back and talk about TimeSync messages at some point in time.  Maybe some of those issues will go away with the TimingApp (and the associated FakeTimingApp, if that is still in the plan), when it becomes available.  We can/should talk about this, as you suggest.

In somewhat related news, I noticed that TriggerRecords at the end of a run can occasionally have missing Fragments.  From the tests that I've done so far, I suspect that this issue pre-dated your TRBuilder changes, but that remains to be confirmed.  

The test in which I noticed this was in a one-process system that had 10 links and no slowdown factor (factor == 1).  The computer on which I'm running the test may not be keeping up, and that may be contributing to the problem.

**Comment by bieryAtFnal** [comment]
With a change to the order in which the Stop commands are sent to the processes, I haven't seen missing Fragments at end run (either with, or without, the TRBuilder change).  
So, my sense is that the TRBuilder changes look good so far.

**Comment by mroda88** [comment]
When we have a lot of links, I sometimes see things like
```bash
2021-May-05 17:39:44,091 LOG [void dunedaq::readout::ReadoutModel<RawType, RequestHandlerType, LatencyBufferType, RawDataProcessorType>::run_timesync() [with RawType = dunedaq::readout::types::WIB_SUPERCHUNK_STRUCT; RequestHandlerType = dunedaq::readout::WIBRequestHandler; LatencyBufferType = dunedaq::readout::ContinousLatencyBufferModel<dunedaq::readout::types::WIB_SUPERCHUNK_STRUCT>; RawDataProcessorType = dunedaq::readout::WIBFrameProcessor] at /nfs/home/maroda/DAQ/TRBuilder/sourcecode/readout/src/ReadoutModel.hpp:242] Timesync with DAQ time 0 won't be sent out as it's an invalid sync.
```
But this is on the readout side and not surprising since the timeout is 0. Apart from that, the tests went all ok using np04-srv-028.

**Review by bieryAtFnal — APPROVED** [review]
Looks good to me

**Pull request merged**
