### PR TITLE
Independent DFO

### PR DESCRIPTION
**Pull request by mroda88**
This PR changes the configurations to allow the DFO to live in its own application.

### CODE REVIEW

**Comment by mroda88** [comment]
To test this branch, the corresponding PRs need to be obtained from appfwk, dfmessages, dfmodules and trigger

**Comment by plasorak** [comment]
Hi, all the tests that I have run are ok (except the one with DQM, but we expect these to fail), the code looks correct. So as far as I'm concerned this looks good.

**Review by philiprodrigues — APPROVED** [review]
Looks correct to me too. I ran at high trigger rate (200Hz with three RUs) with both the `nanorc` and `newconf` configurations, and I see the trigger being inhibited and the inhibit being lifted in a sensible way

**Comment by mroda88** [comment]
For reference. With 3 RU apps, 3 DF apps, trigger at 1 KHz, number of tokens = 10, free watermark = tokes/2 = 5, the system saturates around 450 Hz. 
Screenshot from 2022-02-09 17-49-16

**Comment by mroda88** [comment]
At the same time with the changes in the DFO to MLT busy signal, the rate of the busy signal transmission is around 40 - 50 Hz.
Screenshot from 2022-02-09 17-51-48

**Comment by mroda88** [comment]
I think this addresses both the points made today. I'd like to have this run go on for a few hours before merging though.

**Comment by mroda88** [comment]
I have a nigh-long run. here are some relevant plots, of the last 12h of the run. As you can see the DFO activity is stable. The accepted trigger rate is around 400 Hz, while the generated triggers were at 1 KHz. All the branches across the repos are also synced with develop, so I think we can merge whenever we want. 
The test was done on the new CentOS machines. 
Screenshot from 2022-02-10 09-45-27
Screenshot from 2022-02-10 09-45-06

**Review by bieryAtFnal — APPROVED** [review]
LGTM

**Pull request merged**
