### PR TITLE
Anders kallesoee/readout consolidation release

### PR DESCRIPTION
**Pull request by andersKallesoee**
Readout conf gen additions

### CODE REVIEW

**Review by floriangroetschla — APPROVED** [review]
Tested it with the consolidation_release branch of readout and the changes look good. This will be necessary to run once this branch is merged to develop in readout.

**Comment by bieryAtFnal** [comment]
When I try to run with a system configuration generated from the following command:
```
python -m minidaqapp.nanorc.mdapp_multiru_gen --host-ru localhost -d $PWD/frames.bin -o . -s 10 --enable-software-tpg mdapp_4proc_swtpg
```
I get the following error from the ReadoutApp.  
```
2021-Nov-12 11:34:21,627 ERROR [void dunedaq::cmdlib::CommandFacility::handle_command(const cmdobj_t&, dunedaq::cmdlib::cmd::CommandReply) at /scratch/dev/sourcecode/cmdlib/src/CommandFacility.cpp:64] Execution of command failed: Caught ers::Issue
	was caused by: 2021-Nov-12 11:34:21,627 ERROR [virtual void dunedaq::readout::DataLinkHandler::init(const data_t&) at /home/biery/dunedaq/12Nov210/sourcecode/readout/plugins/DataLinkHandler.cpp:48]  Couldnt initialize Readout with current Init arguments {"qinfos":[{"dir":"input","inst":"tp_link_0","name":"raw_input"},{"dir":"input","inst":"tp_requests_0","name":"data_requests_0"},{"dir":"output","inst":"tp_fragments_q","name":"data_response_0"},{"dir":"output","inst":"time_sync_q","name":"timesync"}]} Readout Initialization Error: tp_datahandler_2
```
Do we now need to specify additional arguments to the confgen script?

**Comment by bieryAtFnal** [comment]
My testing used the _develop_ branch from the _readout_ repo, since it appears that the consolidation branch has already been merged to _develop_ in that repo.

**Review by bieryAtFnal — APPROVED** [review]
After the change from Florian to change the name of the tp_link --> sw_tp_link queue, these changes passed the integration tests that I ran.

**Pull request merged**
