### PR TITLE
Newconf dqm

### PR DESCRIPTION
**Pull request by jmcarcell**

### CODE REVIEW

**Comment by plasorak** [comment]
All tests are successful (four_process_quick_test.py, readout_type_scan.py, six_process_stop_start_test.py). I think you can merge. :)

**Comment by bieryAtFnal** [comment]
Hmm, I’m seeing the following error when running integtests with DQM and newconf:

Problem(s) found in logfile /tmp/pytest-of-biery/pytest-304/run2/log_dqm0_3336.txt:
2022-Feb-08 09:50:37,808 ERROR [static void ers::ErrorHandler::terminate_handler() at /scratch/dev/sourcecode/ers/src/ErrorHandler.cpp:138] Unhandled 'std::exception' exception has been thrown

was caused by: 2022-Feb-08 09:50:37,808 ERROR [ers::Issue::Issue(const ers::Context&, const std::exception&) at /scratch/dev/sourcecode/ers/src/Issue.cpp:91] Environment variable DETCHANNELMAPS_SHARE is not set

Do I need to do something special?



Some additional questions:

I see that TPSetReceiver is not being used in the trigger app.  N2Q modules are being used instead.  Is that planned or accidental?

I also see that some of the connection names have special characters in them.  For example

  *
"${USER}_test.tpsets_apa(0,)_link1”

Is that expected?

Thanks,
Kurt

On Feb 8, 2022, at 9:44 AM, Pierre Lasorak ***@***.******@***.***>> wrote:



All tests are successful (four_process_quick_test.py, readout_type_scan.py, six_process_stop_start_test.py). I think you can merge. :)

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DUNE-2DDAQ_minidaqapp_pull_122-23issuecomment-2D1032751982&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=lfJn8IlK95ZGuafYS9SD4g&m=AYUAFyBHWmwzO0V1oCcuLy_z2u-ln7_uNftFLIbqnowR_TL9_MUNpbRqPz0rkNAt&s=xfTOFm-bbY05SVxY3-G4UoWHxLUGIrrErvEv9rGg8n4&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AIVBHCQOUI4RPQ6UYCV33ALU2E25TANCNFSM5NVZXINQ&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=lfJn8IlK95ZGuafYS9SD4g&m=AYUAFyBHWmwzO0V1oCcuLy_z2u-ln7_uNftFLIbqnowR_TL9_MUNpbRqPz0rkNAt&s=fkHT9TgAk8ovYiPPKXlFu6rvrmIbrj9nRxokjFC7JIk&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=lfJn8IlK95ZGuafYS9SD4g&m=AYUAFyBHWmwzO0V1oCcuLy_z2u-ln7_uNftFLIbqnowR_TL9_MUNpbRqPz0rkNAt&s=kPO0dHegovcG1FtnshKFkkGkUmqo3RMaGbC9S9_g7HE&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=lfJn8IlK95ZGuafYS9SD4g&m=AYUAFyBHWmwzO0V1oCcuLy_z2u-ln7_uNftFLIbqnowR_TL9_MUNpbRqPz0rkNAt&s=vgMhVJFss3aRByePNQQMzfQ1nLA4sWm2Zdbx5ssAXU4&e=>.

**Comment by plasorak** [comment]
That's weird. I checked out appfwk develop, this branch on minidaqapp, and my branch with the integration tests in the dfmodules. What do you have checked out?

**Comment by jmcarcell** [comment]
The change for `DETCHANNELMAPS_SHARE` was merged in develop `appfwk` two days ago, so it has to be an older version of `appfwk`

**Comment by bieryAtFnal** [comment]
Yes, I didn't have appfwk.  And, I am using a software area based on the nightly right before the commit that Juan mentioned.  If I had used today's nightly, it would have been fine.
A re-test with appfwk added to the software area worked fine.
Sorry for not knowing about the associated change in appfwk.

**Pull request merged**
