### PR TITLE
Documentation updates to provide instructions on configuration options for Minidaq app

### PR DESCRIPTION
**Pull request by carloschavez**
Documentation updates to provide instructions on configuration options for Minidaq app using nanorc.

shows examples on how to run different configurations using nanorc on minidaq app.

### CODE REVIEW

**Comment by jcfreeman2** [comment]
A definite improvement.

**Comment by bieryAtFnal** [comment]
I realize that this Pull Request has already been closed, but I'm going to add some notes to it, in the hope that GitHub will send an email with the contents of this comment.

First off, sorry for not looking at the changes sooner; they look like a good start.  And, apologies if you've already started on some of the changes that I mention below.

Some comments:

- What do you think about adding a link to the new page from the main page?  That seems like it might be useful for users who have become familiar with the basic steps and want to refer back to the configuration help.
- Item 2 seems like it would benefit from a few extra words that describe the options and why a user might want to use them.
- For item 3, I suspect that the -t option got dropped recently.  We should bring it back.  Carlos, can you work on that?  This code change would involve removing the "--hsi-event-period FLOAT" option to the `mdapp_multiru_gen` script, adding back the "-t FLOAT" option, and doing the calculation to convert from seconds to nanoseconds in the script (so that we can give the appropriate value to the HSI).  We should mention this change to Stoyan, if/when we go ahead with it.
- For item 4, I suspect that the -s option slows down the simulated clock in the simulated data.  We should learn exactly what it does and provide some words to that affect on this wiki page.  Also, it would be great to include some text as to why a user might want to do that (e.g. running on a slower computer that can't create data fast enough to match what real electronics can do).

Thanks,
Kurt

**Comment by carloschavez** [comment]
Hi Kurt,

Thanks very much for your input, I agree with your points,  as you said, this is by no means finished.
I will implement more changes in a new pull request.

Thanks,
Carlos

**Comment by carloschavez** [comment]
I have now Implemented the changes requested by Kurt,  will request a new PR.

**Pull request merged**
